export const locationOptions = [
    { value: "", label: "Town" },
    { value: "ANG MO KIO", label: "Ang Mo Kio" },
    { value: "BEDOK", label: "Bedok" },
    { value: "BISHAN", label: "Bishan" },
    { value: "BUKIT BATOK", label: "Bukit Batok" },
    { value: "BUKIT MERAH", label: "Bukit Merah" },
    { value: "BUKIT PANJANG", label: "Bukit Panjang" },
    { value: "BUKIT TIMAH", label: "Bukit Timah" },
    { value: "CENTRAL AREA", label: "Central" },
    { value: "CHOA CHU KANG", label: "Choa Chu Kang" },
    { value: "CLEMENTI", label: "Clementi" },
    { value: "GEYLANG", label: "Geylang" },
    { value: "HOUGANG", label: "Hougang" },
    { value: "JURONG EAST", label: "Jurong East" },
    { value: "JURONG WEST", label: "Jurong West" },
    { value: "KALLANG/WHAMPOA", label: "Kallang/Whampoa" },
    { value: "MARINE PARADE", label: "Marine Parade" },
    { value: "PASIR RIS", label: "Pasir Ris" },
    { value: "PUNGGOL", label: "Punggol" },
    { value: "QUEENSTOWN", label: "Queenstown" },
    { value: "SEMBAWANG", label: "Sembawang" },
    { value: "SENGKANG", label: "Sengkang" },
    { value: "SERANGOON", label: "Serangoon" },
    { value: "TAMPINES", label: "Tampines" },
    { value: "TOA PAYOH", label: "Toa Payoh" },
    { value: "WOODLANDS", label: "Woodlands" },
    { value: "YISHUN", label: "Yishun" }
];
  
export const flatTypeOptions = [
    { value: "", label: "Select" },
    { value: "1 ROOM", label: "1-Room" },
    { value: "2 ROOM", label: "2-Room" },
    { value: "3 ROOM", label: "3-Room" },
    { value: "4 ROOM", label: "4-Room" },
    { value: "5 ROOM", label: "5-Room" },
    { value: "EXECUTIVE", label: "Executive Flats" },
    { value: "MULTI-GENERATION", label: "Multi-Generation" },
];